### ISSUE TITLE
Total loss ratio since June-2023

### ISSUE THREAD

**Issue by batransitrist** [leedrake5/Russia-Ukraine#23]
Hello,

If I understand correctly the total loss ratio shows the ratio of equipment loss since the beginning of the war so for example the fact that it shows about 2.7 in July-2023 does not mean that in July-2023 Russia lost 2.7 more equipment than Ukraine, right?

If this is true, would it be possible to show the numbers only starting with June-2023, so we get a new plot "Total equipment loss since 1-June-2023?
I know that some new discoveries are referring to old data but still it would be a better indication on the recent trend. 
(1-June-2023 roughly corresponds to the start of UA counteroffensive)

thx

**Comment by leedrake5** [comment]
Not sure the right way to address it. Oryx/Jakub report unevenly. A day could be 0 (thus 50/50) focus on Ukrainian backlog (1/99) or Russian backlog (99/1). So there has to be some time increment to average over. There is a daily ratio plot with a loess trend (the quad plot) that captures this, but based on the point scatter you'll see how noisy a daily could be. 

For now the current ratio is the whole war. Note that Ukraine has seen a pretty steady degradation since fall of 2022 when it was close to 4. Though important to note that equipment is not itself a war objective - Ukraine will want to spend equipment to attain strategic objectives. So a change in the ratio doesn't directly map on to progress.

**Comment by batransitrist** [comment]
Why not making a new plot "Total loss ratio since 1-Jun-2023"?

**Comment by leedrake5** [comment]
See [here](https://github.com/leedrake5/Russia-Ukraine/blob/main/summer_2023_offensive.md)

**Comment by batransitrist** [comment]
Thanks!

(just when I was starting to teach myself some R...)
