### ISSUE TITLE
Corrupted data (columns) in Google Spreadsheet

### ISSUE THREAD

**Issue by Alehanbdro** [leedrake5/Russia-Ukraine#32]
There are corrupted data (columns) on all tabs in Google Spreadsheet except 'Original' tab

Example of corrupted data (column's names) on the 'Destroyed' tab:

Russia_Losses_excluding_Recon_Drones_and_Trucks_-_13640,_of_which:_destroyed:_9785,_damaged:_683,_abandoned:_951,_captured:_2221	Russia_Losses_excluding_Recon_Drones_and_Trucks_-_13682,_of_which:_destroyed:_9822,_damaged:_684,_abandoned:_954,_captured:_2222	Russia_Losses_excluding_Recon_Drones_and_Trucks_-_13714,_of_which:_destroyed:_9852,_damaged:_685,_abandoned:_955,_captured:_2222

**Comment by Alehanbdro** [comment]
ref: https://docs.google.com/spreadsheets/d/1bngHbR0YPS7XH1oSA1VxoL4R34z60SJcR3NxguZM9GI

**Comment by leedrake5** [comment]
May need to loop in @scarnecchia on this one. Her [repo](https://github.com/scarnecchia/scrape_oryx) is the main way I scrape data from the Oryx site, though with some mods. Will look into it, thank you for flagging.

**Comment by leedrake5** [comment]
I think I've got it fixed. What happened was this: Oryx (really Jakub) began to include a count of losses which removed some drone types. However, because this number changed every day, it led to column multiplication, since mine is a daily tracker. The good news is that this continual duplication never impacted the numbers after I switched to name-based rather than positional-based tabulations in the sheet. The bad news is that the duplication was leading to steadily longer processing times and putting strain on the server. 

I am going to close for now, but please comment here if you see it again. I had to add a "if the column begins with these characters" qualifier, so it can show up again if the name changes on the Oryx site.
